### ISSUE TITLE
Additions to the board troubleshooting section

### ISSUE THREAD

**Issue by danielhass** [tamberg/mse-tsm-mobcom#2]
Dear @tamberg,

Maybe this is helpful for other Linux users as I ran into this during the board setup.

https://github.com/tamberg/mse-tsm-mobcom/wiki/Feather-nRF52840-Sense

- [Linux only] If you get an upload failed message with the following error - `/dev/ttyACM0 permission denied`:
   - Make sure your user has enough permissions to access `/dev/ttyACM0`
   - Check permissions of `/dev/ttyACM0`: `ls -alh /dev/ttyACM0`
   - Add your user to the corresponding group (e.g. Arch Linux `uucp`) or change permissions of `/dev/ttyACM0`

**Comment by tamberg** [comment]
Thanks, added it to https://github.com/tamberg/mse-tsm-mobcom/wiki/Feather-nRF52840-Sense#troubleshooting
